### PR TITLE
Resolve data to write

### PR DESCRIPTION
**Pull request by thomask**
This allows for fetching data asynchronously for other sources

### CODE REVIEW

**Comment by thomask** [comment]
Sure, we're merging data from several CMSes (Dato for most content and Zendesk Help Center for support articles) and saving them in Dato's format. Without this change we didn't find a possible way to fetch data async.

**Comment by stefanoverna** [comment]
@thomask could you please paste an example?

**Comment by stefanoverna** [comment]
uh. I see. thanks!

**Comment by stefanoverna** [comment]
available in v0.3.35

**Pull request merged**
